### PR TITLE
Doc/api ref site

### PR DESCRIPTION
**Pull request by sandytang886**
please help me review branch doc/api-ref-site

### CODE REVIEW

**Comment by metalalive** [comment]
it looks good to me

**Review by metalalive — APPROVED** [review]
For now, the 3 API endpoints in  [this doc site](https://game-as-a-service.github.io/Pandemic-Reign-of-Cthulhu/doc/api/) look good to me.

**Comment by KalpasWang** [comment]
looks good! I think it's ready to be merged to main branch.

**Comment by metalalive** [comment]
@KalpasWang

you didn't approve the PR, do you know how to do this ?
you should see a web page for reviewer, for all files changed in the PR
 , you click the checkbox for each of the files,
 then click `approve` button with your comment.

**Review by KalpasWang — APPROVED** [review]

**Comment by KalpasWang** [comment]
> @KalpasWang
> 
> you didn't approve the PR, do you know how to do this ? Go to the tab `Files Changed`, it lists all files changed in the PR. You click the checkbox along with the text `viewed`, for each file after reading it, think about whether the change / the code makes sense (<-- important, code review should be a way of communication, since this team embrace async communication) then finally click `approve` button with your comment.

sorry, I've never reviewed other people's PR.
I approved it, is there anything I'm still missing?

**Review by wingtkw — APPROVED** [review]

**Pull request merged**
