### PR TITLE
[Feature] backend env init setup

### PR DESCRIPTION
**Pull request by metalalive**
Implementation for issue #3
- Runtime and dev env setup for python backend 
- Add API endpoint for creating game

@wingtkw  or @teds-lin , can one of you help to review my new PR , thanks

### CODE REVIEW

**Comment by metalalive** [comment]
any feedback / comment are welcome , thanks

**Review by teds-lin — APPROVED** [review]
LGTM

**Comment by metalalive** [comment]
Wait for Wing's approval, to make sure she understands the code in this PR.

**Comment by wingtkw** [comment]
looks good to me

**Review by wingtkw — APPROVED** [review]

**Pull request merged**
