### PR TITLE
Feature: frontend add 2 ui pages

### PR DESCRIPTION
**Pull request by KalpasWang**
brief intro to what I do:

- create `InvestigatorCard` component v2 in `@/components/investigator-card2` folder
- create card picking and level selection 2 ui pages
- remove unused `tailwind.config.ts` file (leave `tailwind.config.js` file)
- add `.prettierrc` file for consistent formating
- convert background and investigator image file from png to webp for faster loading time
- put above images in `public/img` folder
- add `config` folder to save investigators and levels config data

card-picking demo
level-setup demo

### CODE REVIEW

**Comment by KalpasWang** [comment]
@wingtkw 
please help me reviewing this PR🙏

**Comment by wingtkw** [comment]
Let me review it on 15
As I got AL on that day

**Comment by metalalive** [comment]
For curiosity, what does the AL stand or ?

**Comment by wingtkw** [comment]
Annual leave

**Comment by wingtkw** [comment]
For the difficulty options, better to name it as label & value instead
as we can add i18n later

**Comment by wingtkw** [comment]
image

seems like it's a bit too large on screen
can you try to scale a bit

**Comment by KalpasWang** [comment]
> For the difficulty options, better to name it as label & value instead as we can add i18n later

like this?
```javascript
export const levels = [
  {
    label: "Introductory",
  },
  {
    label: "Standard",
  },
  {
    label: "Expert",
  },
];
```

**Comment by wingtkw** [comment]
yes, something like this
so later we can change the label as the i18n key and use something like t('levels.introductory') to translate the levels later
```
export const levels = [
  {
    label: "Introductory",
    value: "introductory"
  },
  {
    label: "Standard",
    value: "standard"
  },
  {
    label: "Expert",
    value: "expert"
  },
];
```

**Comment by KalpasWang** [comment]
@wingtkw 
I added 2 commits to fix the issue you mentioned,
you can review it again.🙏

**Review by wingtkw — APPROVED** [review]

**Comment by metalalive** [comment]
Kalpas , congrats, your first code contribution

**Pull request merged**
