### PR TITLE
[#10] refactor: change code due to separation of concern

### PR DESCRIPTION
**Pull request by metalalive**
- move DTO generating code from `CreateGameUseCase` to `presenter` module
- re-format the code in previous commit, to meet PEP8 styling

see [my comment](https://github.com/Game-as-a-Service/Pandemic-Reign-of-Cthulhu/issues/10#issuecomment-1810582510) in the issue #10 for motivation.

### CODE REVIEW

**Comment by metalalive** [comment]
@wingtkw ,
Remind that it is good practice to always run code-formatter tool ([Python Black](https://github.com/psf/black) in this case) before you submit the code.
It helps your code look cleaner a little bit.
It might be acceptable for some engineers to NOT follow the convention,
For some other engineers (not me) if you don't do that they might yell at you.
So keep in mind with this :+1:  .

**Review by teds-lin — APPROVED** [review]
LGTM

**Comment by metalalive** [comment]
@wingtkw , just remind that please review my code in this PR, thanks

**Comment by metalalive** [comment]
@wingtkw , just remind that please review my code in this PR, thanks again.

**Review by wingtkw — APPROVED** [review]

**Pull request merged**
