### PR TITLE
[Feature]backend CI flow

### PR DESCRIPTION
**Pull request by teds-lin**
實作 https://github.com/Game-as-a-Service/Pandemic-Reign-of-Cthulhu/issues/14

-Backend CI flow
-修正當啟用CI flow時，因test檔名不符合pytest規範，所產生之問題

### CODE REVIEW

**Review by metalalive — APPROVED** [review]
ok , @wingtkw plz help to review this PR, thx

**Comment by metalalive** [comment]
@wingtkw  plz help to review this PR, thx

**Comment by wingtkw** [comment]
test wise - lgtm
suggest refining example in running pytest in readme as
`poetry run pytest -v ./tests/e2e/test_game.py`

**Comment by teds-lin** [comment]
> test wise - lgtm suggest refining example in running pytest in readme as `poetry run pytest -v ./tests/e2e/test_game.py`
@wingtkw 
已修改readme中test example

**Review by metalalive — APPROVED** [review]
LGTM

**Review by wingtkw — APPROVED** [review]

**Pull request merged**
